import cv2
import numpy as np
from matplotlib import pyplot as plt


img = cv2.imread("test.png")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret,thresh = cv2.threshold(gray,20,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,40,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,60,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,80,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,100,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,120,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,140,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,160,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,180,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,200,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,220,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,thresh = cv2.threshold(gray,240,255,cv2.THRESH_BINARY)
cv2.imshow("test", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
